language: node_js

notifications:
    email: false

node_js:
    - '10'

before_install:
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn
    - yarn global add greenkeeper-lockfile

before_script:
    - greenkeeper-lockfile-update

script:
    - yarn ci:build

after_script:
    - greenkeeper-lockfile-upload

after_success:
    - cat ./coverage/lcov.info | yarn coveralls
    - yarn travis-deploy-once "yarn semantic-release"

branches:
    except:
        - /^v\d+\.\d+\.\d+$/
